- hosts: localhost
  gather_facts: False

  vars:
    key_name: my_aws
    region: us-east-2
    image: ami-000e7ce4dd68e7a11
    id: "webserver2"
    sec_group: "{{ id }}-sec"
    ec2_access: 
    ec2_secret: 

  tasks:

    - name: Facts
      block:
        - name: Get instance facts
          ec2_instance_facts:
            aws_access_key: "{{ ec2_access }}"
            aws_secret_key: "{{ ec2_secret }}"
            region: "{{ region }}"
          register: result

        - name: Instances ID
          debug:
            msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
          loop: "{{ result.instances }}"

      tags: always

    - name: Provisioning EC2 instances
      block:

      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file','/home/matt/.ssh/{{ key_name }}.pub')}}"
          region: "{{ region }}"
          aws_access_key: "{{ ec2_access }}"
          aws_secret_key: "{{ ec2_secret }}"
          validate_certs: no

      - name: Create security group
        ec2_group:
          name: "{{ sec_group }}"
          description: "Sec group for app {{ id }}"
          aws_access_key: "{{ ec2_access }}"
          aws_secret_key: "{{ ec2_secret }}"
          region: "{{ region }}"
          rules:
            - proto: tcp
              ports: 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port
        register: result_sec_group

      - name: Provision instance(s)
        ec2:
          region: "{{ region }}"
          aws_access_key: "{{ ec2_access }}"
          aws_secret_key: "{{ ec2_secret }}"
          key_name: "{{ key_name }}"
          #id: "{{ id }}"
          group_id: "{{ result_sec_group.group_id }}"
          image: "{{ image }}"
          instance_type: t2.micro
          wait: true
          count: 1
        register: ec2

      - name: Add newly created host to inventory
        lineinfile:
          dest: /home/matt/Desktop/AWS_Ansible/inventory
          regexp: "{{ item.public_dns_name }}"
          line: "{{ item.public_dns_name }} ansible_user=centos"
          insertafter: "[webserver]"
          state: present
        with_items: "{{ ec2.instances }}"

      - name: Add tag to instance(s)
        ec2_tag:
          region: "{{ region }}"
          aws_access_key: "{{ ec2_access }}"
          aws_secret_key: "{{ ec2_secret }}"
          state: "present"
          resource: "{{ item.id }}"
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Type: Webserver

      - name: Wait for SSH to come up
        wait_for:
          host: "{{ item.public_ip }}"
          port: 22
          state: started
        with_items: "{{ ec2.instances }}"


      tags: ['never', 'create_ec2']
